### ISSUE TITLE
Could not import project

### ISSUE THREAD

**Issue by ashishparmar** [shiburagi/BlockEditText#2]
There is a problem with stylishwidget:stylish library, Can you please change to the stable version?

**Comment by shiburagi** [comment]
Can you me the problem with "stylish widget" library problem?

**Comment by shiburagi** [comment]
if still got the problem and want use stable version of stylish widget, then you can try this approach,
```java

implementation 'com.infideap.blockedittext:block-edittext:0.0.6', {
        exclude group: 'com.app.infideap.stylishwidget', module: 'stylish-widget'
}
implementation 'com.app.infideap.stylishwidget:stylish-widget:1.3.9'

```
