### ISSUE TITLE
Listener when the code entered

### ISSUE THREAD

**Issue by alihabbash** [shiburagi/BlockEditText#3]
Hi, thank you for the awesome library.
I'm just wondering if there is a listener to know when the text sequence entered.
and secondly how can I change the color of the hint
Thanks.

**Comment by shiburagi** [comment]
Hi,

There are two listener available for current version,

1.  `void setTextChangedListener(TextWatcher watcher)`
2. `void setOnCardPrefixListener(OnCardPrefixListener listener)`


Method to change just hint's color for this version not supported yet, 
but you can change the color by using `setHintTextAppearance(R.style.hintStyle)`.
