### ISSUE TITLE
[Question] Is there is a way to get input only when the blockField is filled with number of blocks?

### ISSUE THREAD

**Issue by DasserBasyouni** [shiburagi/BlockEditText#4]
In more explanation, I'm wondering about if there is a listener that listens to inputs only when it fills the whole field, so if bet_numberOfBlock="6" then it will only be notified when 6 strings/ints and in the field.

thank you for your great work

**Comment by shiburagi** [comment]
```amexEditText.setTextChangedListener(TextWatcher watcher)```

I think you can use above method. And below the example.
```java
amexEditText.setTextChangedListener(new TextWatcher() {
    @Override
    public void beforeTextChanged(CharSequence s, int start, int count, int after) {

    }

    @Override
    public void onTextChanged(CharSequence s, int start, int before, int count) {
        if(count==6){
            // do something here
        }
    }

    @Override
    public void afterTextChanged(Editable s) {
    }
});
```

**Comment by DasserBasyouni** [comment]
thank you, I didn't find it when I was searching  in the library

**Comment by shiburagi** [comment]
you're welcome

**Comment by shiburagi** [comment]
btw, i already publish new version, ```implementation 'com.infideap.blockedittext:block-edittext:0.0.7'```

fix some issue with text listener, and u can find the example here,

https://github.com/shiburagi/BlockEditText/blob/master/app/src/main/java/com/infideap/blockedittext/MainActivity.java

**Comment by DasserBasyouni** [comment]
thank you so much
