### ISSUE TITLE
Editing Item at Particular Position Shifts the item

### ISSUE THREAD

**Issue by PritishSawant** [shiburagi/BlockEditText#5]
Suppose I have entered 4 numbers and I want to edit number at 2nd position so when number at 2nd position is removed all the leading items i.e items at 3rd and 4th position move one position back and occupy position 2nd and 3rd. Is it possible to keep the block as empty when an item is removed without shifting the leading items.

**Comment by shiburagi** [comment]
U can try this version, have `setShiftPosition(boolean)` function and `app:bet_shiftPosition="false"` to disable shifting during delete


```groovy
dependencies {
   implementation 'com.infideap.blockedittext:block-edittext:0.1.2'
}
```
